apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "mypostgres-postgresql"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USERNAME: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_PASSWORD: V2I0T1p5dEV3Mg==